sudo: required
dist: trusty

language: csharp
mono: none
dotnet: 2.0.0-preview2-006497

solution: SteamKit2/SteamKit2.sln

install:
    - dotnet restore SteamKit2/SteamKit2.sln
    - dotnet restore Samples/Samples.sln

script:
    - dotnet build -f netstandard1.3 SteamKit2/SteamKit2/SteamKit2.csproj
    - dotnet build -f netcoreapp1.1 SteamKit2/Tests/Tests.csproj
    - dotnet build -f netcoreapp1.1 Resources/SteamLanguageParser/SteamLanguageParser.csproj
    - dotnet build -f netcoreapp1.1 Samples/Samples.sln
    - dotnet test -f netcoreapp1.1 SteamKit2/Tests/Tests.csproj

notifications:
    irc:
        channels:
            - "irc.gamesurge.net#opensteamworks"
        on_success: never
        on_failure: always

cache:
    directories:
        - "~/.local/share/NuGet/Cache"
