sudo: required
dist: trusty

language: csharp
mono: none
dotnet: 1.0.1

solution: SteamKit2/SteamKit2.sln

install:
    - dotnet restore SteamKit2/SteamKit2.sln
    - dotnet restore Samples/Samples.sln

script:
    - dotnet build SteamKit2/SteamKit2.sln
    - dotnet build Samples/Samples.sln
    - dotnet test SteamKit2/SteamKit2.sln

notifications:
    irc:
        channels:
            - "irc.gamesurge.net#opensteamworks"
        on_success: never
        on_failure: always

cache:
    directories:
        - "~/.local/share/NuGet/Cache"
